=== goGetSomeFries/alatka-rule/src/main/resources/alatka-rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://rule.alatka.com" targetNamespace="http://rule.alatka.com">
    <xs:element name="root" type="rootType"/>
    <xs:complexType name="rootType">
        <xs:sequence>
            <xs:element name="alatka-rule" type="alatka-ruleType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="alatka-ruleType">
        <xs:sequence>
            <xs:element type="ruleSetType" name="ruleSet"/>
            <xs:element type="dataSourceType" name="dataSource"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:boolean" name="enabled" use="optional"/>
    </xs:complexType>
    <xs:complexType name="ruleSetType">
        <xs:sequence>
            <xs:element type="ruleType" name="rule" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ruleType">
        <xs:sequence>
            <xs:element type="unitType" name="unit" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="desc" use="required"/>
        <xs:attribute type="xs:boolean" name="enabled" use="optional"/>
        <xs:attribute type="xs:integer" name="priority" use="optional"/>
        <xs:attribute type="xs:integer" name="score" use="optional"/>
    </xs:complexType>
    <xs:complexType name="unitType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:boolean" name="enabled" use="optional"/>
                <xs:attribute type="xs:string" name="dataSource" use="optional"/>
                <xs:attribute type="xs:string" name="path" use="optional"/>
                <xs:attribute type="xs:string" name="expression" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="dataSourceType">
        <xs:sequence>
            <xs:element type="databaseType" name="database" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="redisType" name="redis" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="databaseType">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="scope" use="optional"/>
        <xs:attribute type="xs:boolean" name="enabled" use="optional"/>
        <xs:attribute type="xs:string" name="sql" use="required"/>
        <xs:attribute type="xs:string" name="resultType" use="required"/>
    </xs:complexType>
    <xs:complexType name="redisType">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="scope" use="optional"/>
        <xs:attribute type="xs:boolean" name="enabled" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="key" use="required"/>
        <xs:attribute type="xs:string" name="hashKey" use="optional"/>
        <xs:attribute type="xs:string" name="setKey" use="optional"/>
    </xs:complexType>
</xs:schema>

=== goGetSomeFries/alatka-rule/src/test/resources/riskAnalysis.rule.xml
<?xml version="1.0" encoding="UTF-8" ?>
<alatka-rule xmlns="http://rule.alatka.com"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://rule.alatka.com alatka-rule.xsd">
    <ruleSet enabled="true" desc="欺诈规则组" type="greedy">
        <rule id="" desc="风险账户10星" remark="" enabled="true">
            <unit type="default" path="riskAnalysis/test.av"/>
            <unit type="" path=""/>
        </rule>
        <rule id="" desc="风险账户9星" remark="" enabled="true">
            <unit type="default" path=""/>
            <unit type="" path=""/>
        </rule>
    </ruleSet>
</alatka-rule>
